trigger:
  branches:
    include:
    - master
    - release/*

stages:
- template: build-stage.yml@self
  parameters:
    isRelease: false

#- template: test-stage.yml@self
#  parameters:
#    rs_prerelease_only: true
